### PR TITLE
Fix build with openssl-1.1

### PR DESCRIPTION
**Pull request by adrianreber**
This PR includes three commits which try to fix the build with openssl-1.1. With these patches I can build against openssl-1.1 (see http://koji.fedoraproject.org/koji/taskinfo?taskID=16707389) while still building against older openssl versions. With these changes I was able to log in to a newly set up jabberd test instance.

### CODE REVIEW

**Comment by adrianreber** [comment]
Trying to fix #125

**Comment by gdt** [comment]
Did you test that it still builds (with no additional warnings) and works with 1.0.2?

There are at least two spurious newlines introduced (one each in 2nd and 3rd commits).

The ifdef strategy seems really unfortunate, and adds a lot of code.   Do you know what other programs that use openssl are doing?   What does openssl declare as best practices?  It seems they have created a huge API break, and this is puzzling, so I am wondering if I misunderstand.

**Comment by adrianreber** [comment]
Thanks for the review. I removed the unnecessary new-lines and also some doubled 'return 0;' statements which I copy and pasted.

The code still builds on CentOS7 (openssl-1.0.1e) Fedora 23, 24, 25  (openssl-1.0.2j)and rawhide (which has openssl-1.1). The files I touched are without warnings.

My changes are mainly based on what I have seen other projects doing and reading different openssl man pages from the different releases. Yes, it is not really a nice solution but I have no idea how to do it better.

**Comment by t8m** [comment]
The patch is more ugly than other SW porting from OpenSSL 1.0 API to 1.1 API has. Most of the other SW adds the functions missing in the 1.0 API as compat functions when built against 1.0.x. So it does not have to have any ifdefs in the actual program code only around the implementation of the compat functions.

**Comment by OlegGirko** [comment]
This PR will celebrate one year anniversary in 11 days. Why does it take so long to merge it?

**Comment by scottchiefbaker** [comment]
I can confirm that this patch fixed my problem in #161. Currently I'm using the Fedora package (jabberd-2.6.1-6.fc27.x86_64) that includes this patch and it's working great.

This patch absolutely should get included upstream as c2s crashes constantly without it (at least on Fedora).

**Comment by adrianreber** [comment]
The Fedora package only crashes because it included this patch without the fix from @OlegGirko, so plain jabberd2 does not have the problem (but it does not build with openssl-1.1).

**Comment by scottchiefbaker** [comment]
@adrianreber ahhh gotcha. Thanks for the clarification.

**Comment by jaredmauch** [comment]
I'm interested in seeing this merged as well.

**Pull request merged**
