### PR TITLE
Use pkg-config for openssl and remote the definition of SSL_OP_NO_TICKET

### PR DESCRIPTION
**Pull request by YmrDtnJu**

### CODE REVIEW

**Comment by smokku** [comment]
This change breaks the build on Travis.

**Comment by YmrDtnJu** [comment]
It does, because Travis uses an old version of Ubuntu. Are you sure that openssl 1.0.1 which is unmaintained by Upstream, should still be supported?

**Comment by smokku** [comment]
Could you bump it to 16.04 LTS to fix your PR then? :)

**Comment by YmrDtnJu** [comment]
Me? I don't have access to Travis CI.

And it is just a suggestion to require openssl 1.0.2. I am very open to discuss this with anyone interested.

**Comment by smokku** [comment]
You (kind of) do. ;-)
https://github.com/YmrDtnJu/jabberd2/blob/pkg-config-for-openssl/.travis.yml + `dist: xenial`

**Comment by YmrDtnJu** [comment]
OK, I am new to Travis. I will look into it.

**Comment by YmrDtnJu** [comment]
@smokku This can be merged from my side if it is ok with you. I will create a new PR for other changes to configure.ac.

**Pull request merged**
