### PR TITLE
secure password storage

### PR DESCRIPTION
**Pull request by lifeofguenter**
I would like to introduce some changes which will benefit the current security of password handling.

1) ability to use crypt_blowfish as hash algorithm
2) create secure salt with openssl instead of using "rand()"
3) timing attack secure hash comparison
4) make cost configurable (xml-config)
5) use crypt standard, e.g. we can parse hashes and know:
-> used algorithm
-> optionally: cost
-> salt
-> hash
All in a single retrieval (e.g. without extra data lookups) which enables us also to do rehashing if needed (for example updated algorithm or cost) and totally transparent to the user
6) by using (b)crypt, we can create same secure hashes (even for example for logins) with PHP, Perl, Ruby, Golang (and most probably any other programming language) without looking up "how jabberd2 has done it"
7) currently only mysql-storage is supported, but we would like to see a more "global" approach to this problem, as many storages share the same functionality

Would be happy to hear some feedback :)

Currently only mysql as

### CODE REVIEW

**Comment by chaosworld** [comment]
Hello,

May I ask does this mean lasest version support encrypt password storage? I'm using MySQL with jabberd-2.2.14-6.el6.x86_64 but only with password plaintext storage which I really don't like this part.

**Comment by lifeofguenter** [comment]
if you build from current master, yes.

**Comment by chaosworld** [comment]
Good news. Thanks for reply :)

**Comment by chaosworld** [comment]
Hi, I compiled and installed with latest version jabberd-2.3.2, but still without mysql  user/password encryption storage. May I ask if there's some option need to enable in xml config file?

**Comment by chaosworld** [comment]
Hello,

I solved it by changing <password_type> config in c2s.xml file. Actually, older version jabberd-2.2.14-6 support password encryption storage too, but only with mysql.

**Pull request merged**
